version: "3"

tasks:
    build:
        desc: "Build Init"
        sources:
            - "src/**/*.ts"
            - "tsconfig.json"
            - "../../tsconfig.base.json"
        generates:
            - "dist/**/*.js"
            - "dist/**/*.d.ts"
        cmds:
            - bun run build

    typecheck:
        desc: "Typecheck Init"
        cmds:
            - bun run typecheck

    lint:
        desc: "Lint Init"
        cmds:
            - bun run lint

    format:
        desc: "Format Init"
        cmds:
            - bun run format

    check:
        desc: "Check formatting on Init"
        cmds:
            - bun run format:check

    ci:
        desc: "Run all CI checks"
        cmds:
            - task: typecheck
            - task: lint
            - task: check
