/**
 * @file Dev-only: regenerate `src/game/stable.ts` from CDDA's upstream git tags.
 *
 * Run from the frontier package: `bun scripts/update-stable-releases.ts`.
 * Requires network and `git` on PATH. The runtime never calls this.
 */

import path from "path";

/** One tag's bare SHA and its peeled commit SHA (annotated tags only). */
interface TagRefs {
	bare?: string;
	peeled?: string;
}

/** Upstream CDDA repository whose tags name the stable releases. */
const REPO = "https://github.com/CleverRaven/Cataclysm-DDA.git";

/**
 * Stable tags are numeric (`0.7`, `0.7.1`), hex-letter (`0.G`, `0.E-3`), or the one-off `0.H-RELEASE`; experimental tags match none of these.
 */
const STABLE_TAG = /^0\.([0-9]+(\.[0-9]+)?|[A-Z](-[0-9]+|-RELEASE)?)$/;

/** The generated map this script overwrites. */
const TARGET = path.join(import.meta.dir, "..", "src", "game", "stable.ts");

/** Fetch the raw `git ls-remote --tags` output for the upstream repository. */
async function lsRemoteTags(): Promise<string> {
	const proc = Bun.spawn(["git", "ls-remote", "--tags", REPO], {
		stdout: "pipe",
		stderr: "pipe",
	});

	const stdout = await new Response(proc.stdout).text();
	const exitCode = await proc.exited;

	if (exitCode !== 0)
		throw new Error(`git ls-remote failed (exit ${exitCode})`);

	return stdout;
}

/**
 * Collapse `ls-remote` lines into `tag → { bare, peeled }`, keeping only stable tags.
 */
function collectTags(output: string): Map<string, TagRefs> {
	const tags = new Map<string, TagRefs>();
	const released = new Set<string>();

	for (const line of output.split(/\r?\n/)) {
		const match = line.match(
			/^([0-9a-f]{40})\trefs\/tags\/(.+?)(\^\{\})?$/,
		);

		if (!match) continue;

		const [, sha, tag, peeled] = match;

		if (!STABLE_TAG.test(tag)) continue;

		// * `0.H-RELEASE` is the true `0.H`; it supersedes the incomplete bare `0.H`
		const fromRelease = tag.endsWith("-RELEASE");
		const name = fromRelease ? tag.slice(0, -"-RELEASE".length) : tag;

		if (fromRelease && !released.has(name)) {
			tags.delete(name);
			released.add(name);
		}

		if (!fromRelease && released.has(name)) continue;

		const refs = tags.get(name) ?? {};

		if (peeled) refs.peeled = sha;
		else refs.bare = sha;

		tags.set(name, refs);
	}

	return tags;
}

/**
 * Sort key `[tier, major, point]` for a release name. Numeric releases (tier 0) precede hex-letter ones (tier 1); within a tier, major then point-release order.
 */
function tagOrder(name: string): [number, number, number] {
	const core = name.replace(/^0\./, "");
	const [major, point] = core.split(/[.-]/);

	const numeric = /^[0-9]+$/.test(major);
	const tier = numeric ? 0 : 1;
	const majorValue = numeric ? Number(major) : major.charCodeAt(0);
	const pointValue = point ? Number(point) || 0 : 0;

	return [tier, majorValue, pointValue];
}

/** Render the `stable.ts` module source from the collected tags, sorted by release. */
function render(tags: Map<string, TagRefs>): string {
	const entries = [...tags.entries()]
		.sort(([leftTag], [rightTag]) => {
			const leftOrder = tagOrder(leftTag);
			const rightOrder = tagOrder(rightTag);

			return (
				leftOrder[0] - rightOrder[0] ||
				leftOrder[1] - rightOrder[1] ||
				leftOrder[2] - rightOrder[2]
			);
		})
		.map(([tag, refs]) => {
			const sha = refs.peeled ?? refs.bare;

			return `\t"${sha}": "${tag}",`;
		})
		.join("\n");

	return `/**
 * @file Known CDDA stable-release commit SHAs mapped to their tag names.
 *
 * Generated by \`scripts/update-stable-releases.ts\` — do not edit by hand.
 */

/** Commit SHA (a stable release's peeled tag commit) → release tag name. */
export const STABLE_RELEASES: Record<string, string> = {
${entries}
};
`;
}

/** Fetch, filter, and write the regenerated stable-release map. */
async function main(): Promise<void> {
	const output = await lsRemoteTags();
	const tags = collectTags(output);

	await Bun.write(TARGET, render(tags));

	console.log(`Wrote ${tags.size} stable releases to ${TARGET}`);
}

await main();
