/**
 * @file Known CDDA stable-release commit SHAs mapped to their tag names.
 *
 * Generated by `scripts/update-stable-releases.ts`. Do not edit by hand.
 */

/**
 * Commit SHA (a stable release's peeled tag commit) → release tag name.
 */
export const STABLE_RELEASES: Record<string, string> = {
	c79fcdca2f1af501291e3cdef04aa49b57274105: "0.1",
	"8666490d6ad350158e3e510e798c1734778ff50a": "0.2",
	"5190d7135e22ecbf071d3037f9c8511a62d7ac69": "0.3",
	"0437a6a1dab77012e52667dedc7f39e53de3310e": "0.4",
	"1941b4de719f3fed963cdf3eca0d6eaa6eb0d9ee": "0.5",
	cf80a547ce8eb4b4e8b7d08ab3d29d8af138c379: "0.6",
	"7f7b54571bf343f9f6ec53c01943df55f0d85cd6": "0.7",
	"7c8d5009ac305c669df272fa142b471f187c5976": "0.7.1",
	"99b6fe420302dae4dec4f217c5610b4cdfc1468d": "0.8",
	fe75ac9bd64389cd46a6367c3457fc890f7ce572: "0.9",
	"49d4d71acefb29f71553df7901bd7937ff9ae87d": "0.A",
	"2e9fcf95ccdc59e9e7655795e479545b46adfdde": "0.B",
	"2f891d5f34c84ea4f5f278d7b4bd114144e3524d": "0.C",
	"9c732a5de48928691ab863d3ab275ca7b0e522fc": "0.D",
	"6d30e210733f775a1d4be3a20598e5043b92c37e": "0.E",
	a07ce29fc6deb9639dd13b5447889bade25f27d5: "0.E-1",
	e184c6a74e06cdb572e2b904c8b4989eb47d2c92: "0.E-2",
	cb02195d9fb5ba71f35a105be4104c3d8883065c: "0.E-3",
	bc28921102f05a092c103dd2af265439a9934d61: "0.F",
	"8c7366e8615d924cea231762147fb93787500082": "0.F-1",
	bd09f289fcc8c52baf2fee7f9884f12f85479b1d: "0.F-2",
	ef85f3ce35864947b54113c11cb2eec6bdf8522c: "0.F-3",
	d6ec466140839dd70c1a43671eb4a08b007695c2: "0.G",
	"08f04fd07f028219a65f2f1fc8e73719dc9c954e": "0.H",
	"27939e29b8b4ddc081490d9f51de59a459c88df6": "0.I",
};
